trigger:
  branches:
    include:
      - main

pool: goyal-agent

variables:
  WorkD: '$(System.DefaultWorkingDirectory)\Environment'

steps:
  - task: TerraformInstaller@1
    displayName: terraform install
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTask@5
    displayName: terraform init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(workD)'
      backendServiceArm: 'goyal-app'
      backendAzureRmStorageAccountName: 'storegoyal1121'
      backendAzureRmContainerName: 'cont1'
      backendAzureRmKey: 'test.terraform.tfstate'

  - task: TerraformTask@5
    displayName: terraform plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(workD)'
      environmentServiceNameAzureRM: 'goyal-app'

  - task: TerraformTask@5
    displayName: terraform apply
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(workD)'
      commandOptions: '--auto-approve'
      environmentServiceNameAzureRM: 'goyal-app'

  - task: TerraformTask@5
    displayName: terraform destroy
    inputs:
      provider: 'azurerm'
      command: 'destroy'
      workingDirectory: '$(System.DefaultWorkingDirectory)\Environment'
      commandOptions: '--auto-approve'
      environmentServiceNameAzureRM: 'goyal-app'